### ISSUE TITLE
How to add "percentage sign"?

### ISSUE THREAD

**Issue by kodamirmo** [manumaticx/circularprogress#10]
Hi, thanks for your library, im trying to add '%' sign to the label, but i haven't been  able to do it. 
My code:

```
$.progress.animate({
    value: 78,
   	duration: 500,
    formatValue: function(v){return v + '%';},
    showText: true
});
```

Thanks in advance.

**Comment by manumaticx** [comment]
Hi.
I've just updated the widget to v0.3.3 - now you can do this:
```js
$.progress.formatValue = function(val){ return val + '%'; };
```
