### ISSUE TITLE
Dumb question.. how can I hide and show and update on upload ?

### ISSUE THREAD

**Issue by DouglasHennrich** [manumaticx/circularprogress#11]
Hi
I want to hide my progress and show it when I'm uploading something... how can I do that?

I try $.progress.hide() but it's not a exposed method ):

Also I'm facing a little problem when onsendstream function to update the progress...

~~~
onsendstream:function(evt){
	Ti.API.info('ONSENDSTREAM - PROGRESS: ' + evt.progress.toFixed(3));
	
    if(Math.round(evt.progress * 100) <= 100) {
    	$.progress.setValue(evt.progress.toFixed(3) * 100 );
    }
}
~~~

I'm getting the right progress but sometimes it get weird showing ALOT of numbers then it back to the right %( 10.3% ... 82.5% )

this is my `formatValue` -> `$.progress.formatValue = function(val){ return (val) + '%'};`

Thanks

**Comment by manumaticx** [comment]
Hey @DouglasHennrich 

you could add the progress view to a container view that you hide and show (as a workaround) but I'll update the widget too as it should expose all Ti.UI.View properties and methods.

I use this code for updating the progress when uploading a file, maybe this works for you too:
```js
xhr.onsendstream = function(e){
  $.progress.setValue(Math.floor(e.progress * 100));
};
```

**Comment by DouglasHennrich** [comment]
@manumaticx yea I add it to a another view to hide and show as you said and works fine xD

Android support `e.progress` on `onsendstream` ? I read it is not supported on android side =/

Thanks

**Comment by manumaticx** [comment]
@DouglasHennrich it works fine on android :)

**Comment by DouglasHennrich** [comment]
huuummmm
Thank You very Much Mr.Manumaticx :DD

**Comment by manumaticx** [comment]
:v: :smile:
