### ISSUE TITLE
Ability to handle "click" (tap) events around the circle and update progress?

### ISSUE THREAD

**Issue by ksouthworth** [manumaticx/circularprogress#12]
It would be awesome if this widget could listen for click/tap events around the circle and update the progress value accordingly.

For example, if I tap at any point on the arc of the circle, it would update to that value.

Or event better, publish a "touch" event that includes event args with the calculated value.

**Comment by manumaticx** [comment]
Hm, I'm not sure why you need that kind of functionality on a progress bar. Maybe you should go for a [circular slider](https://github.com/mpociot/TiCircularSlider)?
