### ISSUE TITLE
Animation broken

### ISSUE THREAD

**Issue by alvesl** [manumaticx/circularprogress#13]
Hello!
Thanks for all the work with the module, it looks really good.

I'm having some trouble with animation though, it seems to be lagging.
I also need the ability to change colors after the widget is loaded, so it would be nice to export methods for those - I'm happy to contribute with that, should I send  a PR?

Gif for animation bug: http://www.gfycat.com/WeirdBestFairyfly
Titanium SDK 5.0.2.GA iOS 8.2

**Comment by manumaticx** [comment]
Hi @alvesl,

every PR is very welcome!

`animate` does not work on iOS. Not sure why, if you find a fix for this, please send another PR. Thanks.

**Comment by manumaticx** [comment]
@alvesl you can already change the color after creation! Just do:
```js
$.progress.setProgressColor('yellow');
```
