### ISSUE TITLE
How to get the purple behaviour of your Gif

### ISSUE THREAD

**Issue by yozef** [manumaticx/circularprogress#15]
I liked the behaviors of the purple colored circular progress in your gif. 
I've played around with the backgroundColor, progressColor, progressBackgroundColor, and progressWidth with no prevail.

I should note, the background of the circular progress is transparent. It will be shown over an image.

Anyway I can check the code for that specific progress bar? (I'm sure I can manage it by modifying the widget, however I'm curious if there is a cleaner way). Thanks for this Widget by the way!

**Comment by manumaticx** [comment]
Unfortunatly, transparent background is not supported. What you see in the gif is white on white ;)
