### ISSUE TITLE
Android Blurred round corner

### ISSUE THREAD

**Issue by zumrywahid** [manumaticx/circularprogress#20]
Hi Can you please help me to fix this issue ? the Round is not perfect. its blurred and not looking good. 
this is my setting. 
"#progress": {
	right: 0,
	width: 30,
	height: 30,
	margin: 0,
    backgroundColor:'#fff',
    progressColor:'#F1F0D7',
    progressBackgroundColor:'#4CA8A1',
    progressWidth: 0,
    color: '#33b5e5',
    font: {
       // fontSize: 26,
       // fontFamily: 'Roboto Condensed'
    }
}

![screen shot 2016-06-23 at 6 35 27 am](https://cloud.githubusercontent.com/assets/4329818/16288737/c310eb04-390c-11e6-8347-fe2db63c73bb.png)

**Comment by manumaticx** [comment]
I'm afraid there is no quick fix. This can be considered as a limitation. If you have a look at how simple this implementation is,  you might want to use a native module with better graphic support. Closing this as won't fix.
