### ISSUE TITLE
loader cover when we press more then 50%

### ISSUE THREAD

**Issue by aakashsharmaindore** [manumaticx/circularprogress#21]
Hey, 

When pressed for more than 50%, it completes the loader, but actually it should have backtracked the loader.
![screen shot 2016-07-15 at 7 23 07 pm](https://cloud.githubusercontent.com/assets/14976196/16876527/ca8e545e-4ac1-11e6-8578-21c73142574d.png)

**Comment by manumaticx** [comment]
I'm sorry but I'm not sure if I got you right. So, you are updating the progress over 50% and then want to backtrack to 0? Or are we talking about the animation?
What platform are you using? What code do you use?

**Comment by manumaticx** [comment]
Closing this for now. Feel free to re-open.
