### ISSUE TITLE
Can we add this widget into listview item template?

### ISSUE THREAD

**Issue by snehalhumne** [manumaticx/circularprogress#28]
Hi,

Can we add this widget into the listview item template so that we can show the progress on every item?

**Comment by manumaticx** [comment]
Hi, 

according to the [documentation](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.ListItem), this is not supported by Titanium.

Please follow this Ticket for updates: [ALOY-1220](https://jira.appcelerator.org/browse/ALOY-1220)
