### ISSUE TITLE
Its posible Text + Value?

### ISSUE THREAD

**Issue by Geryy** [manumaticx/circularprogress#29]
i want put Text + value. Photo exemple:

![captura de pantalla 2017-09-26 a las 10 53 52](https://user-images.githubusercontent.com/32294138/30851999-a7a210f6-a2aa-11e7-8a1c-3aa170f4f15b.png)

its all! thanks!

**Comment by manumaticx** [comment]
Hi, it should be possible with `formatValue`. Try something like this:
```
$.progress.formatValue = function(val){ return "custom text\n" + value; };
```

Let me know if this works out.

**Comment by Geryy** [comment]
I test it and.. yes, this work fine! Thanks @manumaticx and nice widget!

**Comment by manumaticx** [comment]
great! thank you <3

**Comment by Geryy** [comment]
Sorry for that but i have a last question. Now i want align the text, any solution?

**Comment by manumaticx** [comment]
Unfortunately you can't apply properties to the label through the widget API. I'll think about how to add this functionality.

To align the text, you have to change the widget code and set `$.label.textAlign = Ti.UI.TEXT_ALIGNMENT_CENTER`

**Comment by Geryy** [comment]
Ok thanks for all :D!

**Comment by manumaticx** [comment]
@Geryy hey, I've just added classes to view and label.

After updating the widget you should be able to style it without hacking the widget source.

```
". circularprogress_label": {
  textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER
}
```
