### ISSUE TITLE
commonJS

### ISSUE THREAD

**Issue by caspahouzer** [manumaticx/circularprogress#4]
Do we have the chance to get this as a commonJS module for using without alloy?

**Comment by manumaticx** [comment]
Check out @rondog's implementation: http://pastie.org/8953493 (this widget is based on the same [Q&A thread](http://developer.appcelerator.com/question/154274/is-there-a-way-to-create-circular-progress-bar)) - hope this helps

**Comment by caspahouzer** [comment]
yes, thanks!

**Comment by Max87ZA** [comment]
Hi manumaticx,
is there any chance to convert this Alloy module to classic CommonJS? Pastie.org is down and I can't get to that code provided in your comment above. 
Thank you
